# Generated by Django 2.1.7 on 2019-02-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kmmaccounts',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('institutionid', models.CharField(blank=True, db_column='institutionId', max_length=32, null=True)),
                ('parentid', models.CharField(blank=True, db_column='parentId', max_length=32, null=True)),
                ('lastreconciled', models.TextField(blank=True, db_column='lastReconciled', null=True)),
                ('lastmodified', models.TextField(blank=True, db_column='lastModified', null=True)),
                ('openingdate', models.DateField(blank=True, db_column='openingDate', null=True)),
                ('accountnumber', models.TextField(blank=True, db_column='accountNumber', null=True)),
                ('accounttype', models.CharField(db_column='accountType', max_length=16)),
                ('accounttypestring', models.TextField(blank=True, db_column='accountTypeString', null=True)),
                ('isstockaccount', models.CharField(blank=True, db_column='isStockAccount', max_length=1, null=True)),
                ('accountname', models.TextField(blank=True, db_column='accountName', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currencyid', models.CharField(blank=True, db_column='currencyId', max_length=32, null=True)),
                ('balance', models.TextField(blank=True, null=True)),
                ('balanceformatted', models.TextField(blank=True, db_column='balanceFormatted', null=True)),
                ('transactioncount', models.TextField(blank=True, db_column='transactionCount', null=True)),
            ],
            options={
                'db_table': 'kmmAccounts',
            },
        ),
        migrations.CreateModel(
            name='Kmmbudgetconfig',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('start', models.DateField()),
                ('xml', models.TextField(blank=True, db_column='XML', null=True)),
            ],
            options={
                'db_table': 'kmmBudgetConfig',
            },
        ),
        migrations.CreateModel(
            name='Kmmcurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isocode', models.CharField(db_column='ISOcode', max_length=3, unique=True)),
                ('name', models.TextField()),
                ('type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('typestring', models.TextField(blank=True, db_column='typeString', null=True)),
                ('symbol1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symbol2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symbol3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symbolstring', models.CharField(blank=True, db_column='symbolString', max_length=255, null=True)),
                ('partsperunit', models.CharField(blank=True, db_column='partsPerUnit', max_length=24, null=True)),
                ('smallestcashfraction', models.CharField(blank=True, db_column='smallestCashFraction', max_length=24, null=True)),
                ('smallestaccountfraction', models.CharField(blank=True, db_column='smallestAccountFraction', max_length=24, null=True)),
            ],
            options={
                'db_table': 'kmmCurrencies',
            },
        ),
        migrations.CreateModel(
            name='Kmmfileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('lastmodified', models.DateField(blank=True, db_column='lastModified', null=True)),
                ('basecurrency', models.CharField(blank=True, db_column='baseCurrency', max_length=3, null=True)),
                ('institutions', models.TextField(blank=True, null=True)),
                ('accounts', models.TextField(blank=True, null=True)),
                ('payees', models.TextField(blank=True, null=True)),
                ('transactions', models.TextField(blank=True, null=True)),
                ('splits', models.TextField(blank=True, null=True)),
                ('securities', models.TextField(blank=True, null=True)),
                ('prices', models.TextField(blank=True, null=True)),
                ('currencies', models.TextField(blank=True, null=True)),
                ('schedules', models.TextField(blank=True, null=True)),
                ('reports', models.TextField(blank=True, null=True)),
                ('kvps', models.TextField(blank=True, null=True)),
                ('daterangestart', models.DateField(blank=True, db_column='dateRangeStart', null=True)),
                ('daterangeend', models.DateField(blank=True, db_column='dateRangeEnd', null=True)),
                ('hiinstitutionid', models.TextField(blank=True, db_column='hiInstitutionId', null=True)),
                ('hipayeeid', models.TextField(blank=True, db_column='hiPayeeId', null=True)),
                ('hiaccountid', models.TextField(blank=True, db_column='hiAccountId', null=True)),
                ('hitransactionid', models.TextField(blank=True, db_column='hiTransactionId', null=True)),
                ('hischeduleid', models.TextField(blank=True, db_column='hiScheduleId', null=True)),
                ('hisecurityid', models.TextField(blank=True, db_column='hiSecurityId', null=True)),
                ('hireportid', models.TextField(blank=True, db_column='hiReportId', null=True)),
                ('encryptdata', models.CharField(blank=True, db_column='encryptData', max_length=255, null=True)),
                ('updateinprogress', models.CharField(blank=True, db_column='updateInProgress', max_length=1, null=True)),
                ('budgets', models.TextField(blank=True, null=True)),
                ('hibudgetid', models.TextField(blank=True, db_column='hiBudgetId', null=True)),
                ('logonuser', models.CharField(blank=True, db_column='logonUser', max_length=255, null=True)),
                ('logonat', models.TextField(blank=True, db_column='logonAt', null=True)),
                ('fixlevel', models.TextField(blank=True, db_column='fixLevel', null=True)),
            ],
            options={
                'db_table': 'kmmFileInfo',
            },
        ),
        migrations.CreateModel(
            name='Kmminstitutions',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('manager', models.TextField(blank=True, null=True)),
                ('routingcode', models.TextField(blank=True, db_column='routingCode', null=True)),
                ('addressstreet', models.TextField(blank=True, db_column='addressStreet', null=True)),
                ('addresscity', models.TextField(blank=True, db_column='addressCity', null=True)),
                ('addresszipcode', models.TextField(blank=True, db_column='addressZipcode', null=True)),
                ('telephone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kmmInstitutions',
            },
        ),
        migrations.CreateModel(
            name='Kmmkeyvaluepairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvptype', models.CharField(db_column='kvpType', max_length=16)),
                ('kvpid', models.CharField(blank=True, db_column='kvpId', max_length=32, null=True)),
                ('kvpkey', models.CharField(db_column='kvpKey', max_length=255)),
                ('kvpdata', models.TextField(blank=True, db_column='kvpData', null=True)),
            ],
            options={
                'db_table': 'kmmKeyValuePairs',
            },
        ),
        migrations.CreateModel(
            name='Kmmpayees',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('addressstreet', models.TextField(blank=True, db_column='addressStreet', null=True)),
                ('addresscity', models.TextField(blank=True, db_column='addressCity', null=True)),
                ('addresszipcode', models.TextField(blank=True, db_column='addressZipcode', null=True)),
                ('addressstate', models.TextField(blank=True, db_column='addressState', null=True)),
                ('telephone', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('defaultaccountid', models.CharField(blank=True, db_column='defaultAccountId', max_length=32, null=True)),
                ('matchdata', models.TextField(blank=True, db_column='matchData', null=True)),
                ('matchignorecase', models.CharField(blank=True, db_column='matchIgnoreCase', max_length=1, null=True)),
                ('matchkeys', models.TextField(blank=True, db_column='matchKeys', null=True)),
            ],
            options={
                'db_table': 'kmmPayees',
            },
        ),
        migrations.CreateModel(
            name='Kmmprices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromid', models.CharField(db_column='fromId', max_length=32)),
                ('toid', models.CharField(db_column='toId', max_length=32)),
                ('pricedate', models.DateField(db_column='priceDate')),
                ('price', models.TextField()),
                ('priceformatted', models.TextField(blank=True, db_column='priceFormatted', null=True)),
                ('pricesource', models.TextField(blank=True, db_column='priceSource', null=True)),
            ],
            options={
                'db_table': 'kmmPrices',
            },
        ),
        migrations.CreateModel(
            name='Kmmreportconfig',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('xml', models.TextField(blank=True, db_column='XML', null=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'kmmReportConfig',
            },
        ),
        migrations.CreateModel(
            name='Kmmschedulepaymenthistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedid', models.CharField(db_column='schedId', max_length=32)),
                ('paydate', models.DateField(db_column='payDate')),
            ],
            options={
                'db_table': 'kmmSchedulePaymentHistory',
            },
        ),
        migrations.CreateModel(
            name='Kmmschedules',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('typestring', models.TextField(blank=True, db_column='typeString', null=True)),
                ('occurence', models.PositiveSmallIntegerField()),
                ('occurencemultiplier', models.PositiveSmallIntegerField(db_column='occurenceMultiplier')),
                ('occurencestring', models.TextField(blank=True, db_column='occurenceString', null=True)),
                ('paymenttype', models.TextField(blank=True, db_column='paymentType', null=True)),
                ('paymenttypestring', models.TextField(blank=True, db_column='paymentTypeString', null=True)),
                ('startdate', models.DateField(db_column='startDate')),
                ('enddate', models.DateField(blank=True, db_column='endDate', null=True)),
                ('fixed', models.CharField(max_length=1)),
                ('autoenter', models.CharField(db_column='autoEnter', max_length=1)),
                ('lastpayment', models.DateField(blank=True, db_column='lastPayment', null=True)),
                ('nextpaymentdue', models.DateField(blank=True, db_column='nextPaymentDue', null=True)),
                ('weekendoption', models.TextField(db_column='weekendOption')),
                ('weekendoptionstring', models.TextField(blank=True, db_column='weekendOptionString', null=True)),
            ],
            options={
                'db_table': 'kmmSchedules',
            },
        ),
        migrations.CreateModel(
            name='Kmmsecurities',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('symbol', models.TextField(blank=True, null=True)),
                ('type', models.PositiveSmallIntegerField()),
                ('typestring', models.TextField(blank=True, db_column='typeString', null=True)),
                ('smallestaccountfraction', models.CharField(blank=True, db_column='smallestAccountFraction', max_length=24, null=True)),
                ('tradingmarket', models.TextField(blank=True, db_column='tradingMarket', null=True)),
                ('tradingcurrency', models.CharField(blank=True, db_column='tradingCurrency', max_length=3, null=True)),
            ],
            options={
                'db_table': 'kmmSecurities',
            },
        ),
        migrations.CreateModel(
            name='Kmmsplits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(db_column='transactionId', max_length=32)),
                ('txtype', models.CharField(blank=True, db_column='txType', max_length=1, null=True)),
                ('splitid', models.PositiveSmallIntegerField(db_column='splitId')),
                ('payeeid', models.CharField(blank=True, db_column='payeeId', max_length=32, null=True)),
                ('reconciledate', models.TextField(blank=True, db_column='reconcileDate', null=True)),
                ('action', models.CharField(blank=True, max_length=16, null=True)),
                ('reconcileflag', models.CharField(blank=True, db_column='reconcileFlag', max_length=1, null=True)),
                ('value', models.TextField()),
                ('valueformatted', models.TextField(blank=True, db_column='valueFormatted', null=True)),
                ('shares', models.TextField()),
                ('sharesformatted', models.TextField(blank=True, db_column='sharesFormatted', null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('priceformatted', models.TextField(blank=True, db_column='priceFormatted', null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('accountid', models.CharField(db_column='accountId', max_length=32)),
                ('checknumber', models.CharField(blank=True, db_column='checkNumber', max_length=32, null=True)),
                ('postdate', models.TextField(blank=True, db_column='postDate', null=True)),
                ('bankid', models.TextField(blank=True, db_column='bankId', null=True)),
            ],
            options={
                'db_table': 'kmmSplits',
            },
        ),
        migrations.CreateModel(
            name='Kmmtransactions',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('txtype', models.CharField(blank=True, db_column='txType', max_length=1, null=True)),
                ('postdate', models.TextField(blank=True, db_column='postDate', null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('entrydate', models.TextField(blank=True, db_column='entryDate', null=True)),
                ('currencyid', models.CharField(blank=True, db_column='currencyId', max_length=3, null=True)),
                ('bankid', models.TextField(blank=True, db_column='bankId', null=True)),
            ],
            options={
                'db_table': 'kmmTransactions',
            },
        ),
    ]
